"""Python-first typed tools hosted behind the OpenCode custom-tool adapter."""
from __future__ import annotations

import asyncio
import inspect
import json
import os
import re
import secrets
import tempfile
import threading
from collections.abc import Callable, Mapping
from dataclasses import asdict, dataclass, is_dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import jsonschema

from ..permissions import Access

_TOOL_NAME = re.compile(r"^[a-z][a-z0-9_-]*$")
_GENERATED_HEADER = "// Generated by Spiritus. Do not edit.\n"
_MAX_REQUEST_BYTES = 1024 * 1024


@dataclass(frozen=True, slots=True)
class ToolContext:
    session_id: str = ""
    message_id: str = ""
    agent: str = ""
    directory: str = ""
    worktree: str = ""

    @classmethod
    def from_payload(cls, payload: Mapping[str, Any]) -> ToolContext:
        return cls(
            session_id=str(payload.get("sessionID", "")),
            message_id=str(payload.get("messageID", "")),
            agent=str(payload.get("agent", "")),
            directory=str(payload.get("directory", "")),
            worktree=str(payload.get("worktree", "")),
        )


@dataclass(frozen=True, slots=True)
class Tool:
    """A validated Python callable exposed to selected agents."""

    name: str
    description: str
    input_schema: Mapping[str, Any]
    handler: Callable[..., Any]
    access: Access | str = Access.ALLOW
    output_schema: Mapping[str, Any] | None = None

    def __post_init__(self) -> None:
        name = self.name.strip()
        if not _TOOL_NAME.fullmatch(name):
            raise ValueError(
                "tool name must start with a lowercase letter and contain only "
                "lowercase letters, digits, '-' or '_'"
            )
        description = self.description.strip()
        if not description:
            raise ValueError("tool description cannot be empty")
        schema = dict(self.input_schema)
        jsonschema.Draft202012Validator.check_schema(schema)
        if schema.get("type") != "object":
            raise ValueError("tool input_schema must describe a JSON object")
        if not callable(self.handler):
            raise TypeError("tool handler must be callable")
        if self.output_schema is not None:
            jsonschema.Draft202012Validator.check_schema(dict(self.output_schema))
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "description", description)
        object.__setattr__(self, "input_schema", schema)
        object.__setattr__(self, "access", Access.parse(self.access))
        if self.output_schema is not None:
            object.__setattr__(self, "output_schema", dict(self.output_schema))

    @property
    def engine_name(self) -> str:
        return f"spiritus_{self.name.replace('-', '_')}"

    def invoke(self, arguments: Mapping[str, Any], context: ToolContext) -> Any:
        value = dict(arguments)
        jsonschema.validate(value, dict(self.input_schema))
        signature = inspect.signature(self.handler)
        try:
            signature.bind(value, context)
        except TypeError:
            try:
                signature.bind(value)
            except TypeError as exc:
                raise TypeError(
                    "tool handlers must accept (arguments) or (arguments, context)"
                ) from exc
            result = self.handler(value)
        else:
            result = self.handler(value, context)
        if inspect.isawaitable(result):
            result = asyncio.run(result)
        if is_dataclass(result) and not isinstance(result, type):
            result = asdict(result)
        if self.output_schema is not None:
            jsonschema.validate(result, dict(self.output_schema))
        # Fail at the Python boundary, not later inside the generated JS shim.
        json.dumps(result, ensure_ascii=False)
        return result

    def compile(self, project_root: Path) -> Path:
        directory = Path(project_root) / ".opencode" / "tools"
        directory.mkdir(parents=True, exist_ok=True)
        target = directory / f"{self.engine_name}.ts"
        if target.exists() and not target.read_text(encoding="utf-8").startswith(
            _GENERATED_HEADER
        ):
            raise RuntimeError(f"refusing to overwrite non-Spiritus tool file: {target}")
        body = _GENERATED_HEADER + self._typescript()
        fd, temporary = tempfile.mkstemp(prefix=".tool-", suffix=".tmp", dir=directory)
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(body)
            os.replace(temporary, target)
        except BaseException:
            try:
                Path(temporary).unlink()
            except OSError:
                pass
            raise
        return target

    def _typescript(self) -> str:
        properties = self.input_schema.get("properties", {})
        required = set(self.input_schema.get("required", []))
        args = []
        for name, schema in properties.items():
            expression = _zod_expression(schema)
            if name not in required:
                expression += ".optional()"
            args.append(f"    {json.dumps(name)}: {expression},")
        args_body = "\n".join(args)
        return (
            'import { tool } from "@opencode-ai/plugin"\n\n'
            "export default tool({\n"
            f"  description: {json.dumps(self.description)},\n"
            "  args: {\n"
            f"{args_body}\n"
            "  },\n"
            "  async execute(args, context) {\n"
            "    const base = process.env.SPIRITUS_TOOL_URL\n"
            "    const token = process.env.SPIRITUS_TOOL_TOKEN\n"
            "    if (!base || !token) throw new Error(\"Spiritus tool host is unavailable\")\n"
            f"    const response = await fetch(`${{base}}/tools/{self.engine_name}`, {{\n"
            "      method: \"POST\",\n"
            "      headers: {\n"
            "        \"authorization\": `Bearer ${token}`,\n"
            "        \"content-type\": \"application/json\",\n"
            "      },\n"
            "      body: JSON.stringify({\n"
            "        args,\n"
            "        context: {\n"
            "          sessionID: context.sessionID, messageID: context.messageID,\n"
            "          agent: context.agent, directory: context.directory,\n"
            "          worktree: context.worktree,\n"
            "        },\n"
            "      }),\n"
            "    })\n"
            "    const payload = await response.json()\n"
            "    if (!response.ok) throw new Error(payload.error || `Tool failed (${response.status})`)\n"
            "    return typeof payload.result === \"string\"\n"
            "      ? payload.result\n"
            "      : JSON.stringify(payload.result)\n"
            "  },\n"
            "})\n"
        )


def _zod_expression(schema: Mapping[str, Any]) -> str:
    description = schema.get("description")
    if "enum" in schema and all(isinstance(item, str) for item in schema["enum"]):
        expression = f"tool.schema.enum({json.dumps(schema['enum'])})"
    else:
        schema_type = schema.get("type")
        if schema_type == "string":
            expression = "tool.schema.string()"
        elif schema_type == "number":
            expression = "tool.schema.number()"
        elif schema_type == "integer":
            expression = "tool.schema.number().int()"
        elif schema_type == "boolean":
            expression = "tool.schema.boolean()"
        elif schema_type == "array":
            expression = f"tool.schema.array({_zod_expression(schema.get('items', {}))})"
        elif schema_type == "object":
            nested = []
            required = set(schema.get("required", []))
            for name, child in schema.get("properties", {}).items():
                child_expression = _zod_expression(child)
                if name not in required:
                    child_expression += ".optional()"
                nested.append(f"{json.dumps(name)}: {child_expression}")
            expression = "tool.schema.object({" + ", ".join(nested) + "})"
        else:
            expression = "tool.schema.any()"
    if description:
        expression += f".describe({json.dumps(str(description))})"
    return expression


class ToolServer:
    """Loopback-only authenticated executor for generated OpenCode shims."""

    def __init__(self, tools: tuple[Tool, ...]):
        self._tools = {tool.engine_name: tool for tool in tools}
        self._token = secrets.token_urlsafe(32)
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None
        self._calls: list[dict[str, Any]] = []
        self._lock = threading.RLock()

    @property
    def calls(self) -> tuple[dict[str, Any], ...]:
        with self._lock:
            return tuple(self._calls)

    def start(self) -> dict[str, str]:
        if self._server is not None:
            return self.environment
        owner = self

        class Handler(BaseHTTPRequestHandler):
            def do_POST(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
                owner._handle(self)

            def log_message(self, format: str, *args: Any) -> None:
                return

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()
        return self.environment

    @property
    def environment(self) -> dict[str, str]:
        if self._server is None:
            raise RuntimeError("tool server has not been started")
        port = self._server.server_address[1]
        return {
            "SPIRITUS_TOOL_URL": f"http://127.0.0.1:{port}",
            "SPIRITUS_TOOL_TOKEN": self._token,
        }

    def _handle(self, request: BaseHTTPRequestHandler) -> None:
        if request.headers.get("authorization") != f"Bearer {self._token}":
            self._write(request, HTTPStatus.UNAUTHORIZED, {"error": "unauthorized"})
            return
        prefix = "/tools/"
        if not request.path.startswith(prefix):
            self._write(request, HTTPStatus.NOT_FOUND, {"error": "unknown tool"})
            return
        tool = self._tools.get(request.path[len(prefix):])
        if tool is None:
            self._write(request, HTTPStatus.NOT_FOUND, {"error": "unknown tool"})
            return
        try:
            length = int(request.headers.get("content-length", "0"))
            if length < 0 or length > _MAX_REQUEST_BYTES:
                self._write(
                    request,
                    HTTPStatus.REQUEST_ENTITY_TOO_LARGE,
                    {"error": "tool request exceeds the 1 MiB limit"},
                )
                return
            payload = json.loads(request.rfile.read(length) or b"{}")
            arguments = payload.get("args", {})
            context = ToolContext.from_payload(payload.get("context", {}))
            result = tool.invoke(arguments, context)
        except (json.JSONDecodeError, jsonschema.ValidationError, ValueError) as exc:
            self._record(tool, arguments if "arguments" in locals() else {}, None, str(exc))
            self._write(request, HTTPStatus.BAD_REQUEST, {"error": str(exc)})
            return
        except BaseException as exc:
            self._record(tool, arguments if "arguments" in locals() else {}, None, str(exc))
            self._write(request, HTTPStatus.INTERNAL_SERVER_ERROR, {"error": str(exc)})
            return
        self._record(tool, arguments, result, None, context)
        self._write(request, HTTPStatus.OK, {"result": result})

    def _record(
        self,
        tool: Tool,
        arguments: Any,
        result: Any,
        error: str | None,
        context: ToolContext | None = None,
    ) -> None:
        with self._lock:
            self._calls.append({
                "tool": tool.name,
                "engine_name": tool.engine_name,
                "arguments": arguments,
                "result": result,
                "error": error,
                "context": asdict(context) if context is not None else {},
            })

    @staticmethod
    def _write(
        request: BaseHTTPRequestHandler,
        status: HTTPStatus,
        payload: Mapping[str, Any],
    ) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        request.send_response(status.value)
        request.send_header("content-type", "application/json; charset=utf-8")
        request.send_header("content-length", str(len(body)))
        request.end_headers()
        request.wfile.write(body)

    def stop(self) -> None:
        server, self._server = self._server, None
        thread, self._thread = self._thread, None
        if server is None:
            return
        server.shutdown()
        server.server_close()
        if thread is not None:
            thread.join(timeout=5)


__all__ = ["Tool", "ToolContext", "ToolServer"]
